services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      APP_ENV: dev
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./dev-php.ini:/usr/local/etc/php/conf.d/99-dev.ini