- route: /
  page: home

- route: /about
  page: about

- route: /homelab
  page: homelab

- route: /apps
  page: apps

- route: /devops
  page: devops

- route: /imprint
  page: imprint

- route: /privacy
  page: privacy

- route: /apps/website
  page: apps/website

- route: /apps/website/dsl
  page: apps/website/dsl

- route: /apps/website/assets
  page: apps/website/assets

- route: /apps/website/content
  page: apps/website/content

- route: /apps/website/templates
  page: apps/website/templates

- route: /apps/website/php
  page: apps/website/php

- route: /apps/website/cicd
  page: apps/website/cicd

- route: /app/website
  page: apps/website

- route: /app/website/dsl
  page: apps/website/dsl

- route: /app/website/assets
  page: apps/website/assets

- route: /app/website/content
  page: apps/website/content

- route: /app/website/templates
  page: apps/website/templates

- route: /app/website/php
  page: apps/website/php

- route: /app/website/cicd
  page: apps/website/cicd
